### ISSUE TITLE
Quality score infinite for tasks without upper bound

### ISSUE THREAD

**Issue by jendrikseipp** [ipc2023-classical/scripts#1]
@ipc2023-classical/organizers While working on the scripts for the learning track I saw that you use `float("inf")` as the default upper bound. This means that the quality score is infinite for tasks without an upper bound. Since that's probably something we want to avoid, I guess you have upper bounds for all tasks? 

https://github.com/ipc2023-classical/scripts/blob/2f3cf39e76f8ecac3e2bea80681ba32ac269d0fa/experiments/report.py#L28

**Comment by FlorianPommerening** [comment]
Yes, we have finite bounds on all tasks. I think defining the score of a finite solution to be infinite is fair, in cases where you don't have an upper bound: a solution of any quality is "infinitely better" than not having any solution. But I can see how it could cause problems with missing bounds.
